-- Query 1

SELECT BILLINGCOUNTRY COUNT(INVOICEID)
FROM INVOICE
GROUP BY BILLINGCOUNTRY
ORDER BY COUNT(INVOICEID) DESC;

-- query 2

SELECT BILLINGCITY, SUM(TOTAL) AS T
FROM INVOICE
GROUP BY BILLINGCITY
ORDER BY T DESC
LIMIT 1;

--QUERY 3

SELECT C.CUSTOMERID, C.FIRSTNAME, C.LASTNAME, SUM(I.TOTAL)
FROM CUSTOMER C JOIN INVOICE I ON C.CUSTOMERID = I.CUSTOMERID
GROUP BY C.CUSTOMERID
ORDER BY SUM(I.TOTAL) DESC
limit 1;

--query 3a

SELECT C.CUSTOMERID, C.FIRSTNAME, C.LASTNAME, SUM(I.TOTAL)
FROM CUSTOMER C NATURAL JOIN INVOICE I 
GROUP BY C.CUSTOMERID
ORDER BY SUM(I.TOTAL) DESC
limit 1;


--QUERY 3B
SELECT C.CUSTOMERID, C.FIRSTNAME, C.LASTNAME, SUM(I.TOTAL)
FROM CUSTOMER C, INVOICE I 
WHERE C.CUSTOMERID = I.CUSTOMERID
GROUP BY C.CUSTOMERID
ORDER BY SUM(I.TOTAL) DESC
limit 1;


-- QUERY 4

SELECT DISTINCT C.EMAIL, C.FIRSTNAME, C.LASTNAME, G.NAME 
FROM CUSTOMER C
	JOIN INVOICE I ON C.CUSTOMERID = I.CUSTOMERID
	JOIN INVOICELine IL ON I.INVOICEID = IL.INVOICEID
	JOIN TRACK T ON IL.TRACKID = T.TRACKID
	JOIN GENRE G ON T.GENREID = G.GENREID
WHERE G.NAME = 'Rock'
ORDER BY C.EMAIL;

-- QUERY 4A
SELECT DISTINCT C.EMAIL, C.FIRSTNAME, C.LASTNAME, G.NAME 
FROM CUSTOMER C, INVOICE I, INVOICELine IL, TRACK T,GENRE G
WHERE C.CUSTOMERID = I.CUSTOMERID AND I.INVOICEID = IL.INVOICEID
	AND IL.TRACKID = T.TRACKID AND T.GENREID = G.GENREID 
	AND G.NAME = 'Rock'
	
ORDER BY C.EMAIL;



-- QUERY 5

SELECT AR.NAME,
  	COUNT(T.NAME)
  FROM TRACK T
  JOIN GENRE G ON T.GENREID = G.GENREID
  JOIN ALBUM AL ON AL.ALBUMID = T.ALBUMID
  JOIN ARTIST AR ON AR.ARTISTID = AL.ARTISTID
  WHERE G.NAME = 'Rock'
  GROUP BY AR.NAME
  ORDER BY COUNT(T.NAME) DESC

  -- QUERY 6


  SELECT DISTINCT G.NAME,
  	COUNT(T.NAME)
  FROM CUSTOMER C
  JOIN INVOICE I ON I.CUSTOMERID = C.CUSTOMERID
  JOIN INVOICELINE IL ON IL.INVOICEID = I.INVOICEID
  JOIN TRACK T ON T.TRACKID = IL.TRACKID
  JOIN GENRE G ON G.GENREID = T.GENREID
  WHERE C.CUSTOMERID = 12
  GROUP BY G.NAME
  ORDER BY G.NAME;

  -- QUERY 7
  SELECT C.LASTNAME,C.FIRSTNAME, G.NAME ,
  SUM(IL.UNITPRICE)
  FROM CUSTOMER C
  JOIN INVOICE I ON I.CUSTOMERID = C.CUSTOMERID
  JOIN INVOICELINE IL ON IL.INVOICEID = I.INVOICEID
  JOIN TRACK T ON T.TRACKID = IL.TRACKID
  JOIN GENRE G ON G.GENREID = T.GENREID
  WHERE C.CUSTOMERID = 13
  GROUP BY C.LASTNAME, C.FIRSTNAME, G.NAME
  ORDER BY C.LASTNAME;


--QUERY 8


SELECT C.CUSTOMERID,C.LASTNAME,C.FIRSTNAME,
  G.NAME ,
  SUM(IL.UNITPRICE)
  FROM CUSTOMER C
  JOIN INVOICE I ON I.CUSTOMERID = C.CUSTOMERID
  JOIN INVOICELINE IL ON IL.INVOICEID = I.INVOICEID
  JOIN TRACK T ON T.TRACKID = IL.TRACKID
  JOIN GENRE G ON G.GENREID = T.GENREID
  GROUP BY C.CUSTOMERID,C.LASTNAME,C.FIRSTNAME,G.NAME
  ORDER BY C.CUSTOMERID;


 -- QUERY 9

 SELECT G.NAME ,
  	SUM(IL.UNITPRICE) SUMUNIT
  FROM CUSTOMER C
  JOIN INVOICE I ON I.CUSTOMERID = C.CUSTOMERID
  JOIN INVOICELINE IL ON IL.INVOICEID = I.INVOICEID
  JOIN TRACK T ON T.TRACKID = IL.TRACKID
  JOIN GENRE G ON G.GENREID = T.GENREID
  GROUP BY G.NAME
  ORDER BY SUMUNIT DESC;


 -- QUERY 10
--NOT INCLUDED IN THE EXAM

SELECT *
  FROM
  	(SELECT C.CUSTOMERID,
  	C.FIRSTNAME || ' ' || C.LASTNAME AS CUSTOMER,SUM(IL.UNITPRICE) AS TOTAL
  					FROM CUSTOMER C
  					JOIN INVOICE I ON I.CUSTOMERID=C.CUSTOMERID
  					JOIN INVOICELINE IL ON IL.INVOICEID = I.INVOICEID
  					JOIN TRACK T ON T.TRACKID = IL.TRACKID
  					WHERE COUNTRY = 'USA'
  					GROUP BY 1,2
  					ORDER BY 3 DESC) AS X;

 -- QUERY 11

SELECT C.COUNTRY,
  	COUNT(C.CUSTOMERID)
  FROM CUSTOMER C
  GROUP BY C.COUNTRY
  ORDER BY C.COUNTRY;

-- QUERY 12

SELECT C.COUNTRY,
  	C.FIRSTNAME || ' ' || C.LASTNAME AS CUSTOMER,
  	SUM(I.TOTAL) TOTALS
  FROM INVOICE I
  JOIN CUSTOMER C ON C.CUSTOMERID = I.CUSTOMERID
  GROUP BY C.COUNTRY, CUSTOMER
  ORDER BY TOTALS DESC;

 -- QUERY 13

 SELECT G.NAME,
  	COUNT(T.TRACKID) CTRACK
  FROM TRACK T
  JOIN GENRE G ON T.GENREID = G.GENREID
  GROUP BY G.NAME
  ORDER BY CTRACK DESC;



